version: '3.8'

services:
  db:
    image: postgres:15
    container_name: soulBase_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data_soulBase:/var/lib/postgresql/data

  event-listener:
    build:
      context: ./apps/event-listener
    command: node index.ts
    restart: always

volumes:
  db_data_soulBase:
